object_type: "global_settings"
overrides:
  "xmla.auth.token.enabled": true
  "auth.user.normalize.lowercase": false
  "query.factless.ignoreIncidentalFilter": false
  "aggregates.prediction.reports.storePredictorData": False
  
